---
server:
  port: 8080
  contextPath: /
---
spring:
  profiles: local,default
datasource:
  sampleapp:
    url: jdbc:h2:~/test;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    multipart.enabled : true

    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---



